development:
  secret_key_base: ENV['_FIGARO_secret_key_base']
  secret_token: ENV['_FIGARO_secret_token']


production:
  secret_key_base: ENV['_FIGARO_secret_key_base']
  secret_token: ENV['_FIGARO_secret_token']
